blueprint:
  name: Sync Switch with Lights
  description: Turn on a switch when motion is detected.
  domain: automation
  source_url: https://github.com/axelcypher/HA-blueprint-sync-switch-with-lights/
  input:
    switch_target:
      name: Switch Entity
      selector:
        target:
          entity:
            domain: switch
    light_target:
      name: Light Entity
      selector:
        target:
          entity:
            domain: light
            
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input switch_target
action:
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    entity_id: !input light_target
